// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtTbL63HfuvcJAbKjQ6miLb8h5XmakI3o',
    appId: '1:716525555959:web:3de2308f278e22f90103f2',
    messagingSenderId: '716525555959',
    projectId: 'glowify-final',
    authDomain: 'glowify-final.firebaseapp.com',
    storageBucket: 'glowify-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaHdKmNtREG0PqnZKuEKpyKoBDCVuvoqc',
    appId: '1:716525555959:android:1b075a47b35264de0103f2',
    messagingSenderId: '716525555959',
    projectId: 'glowify-final',
    storageBucket: 'glowify-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsrPj6Y0TxxmOrus66MXkfJSyQDZ23u98',
    appId: '1:716525555959:ios:35ac28229ddd86120103f2',
    messagingSenderId: '716525555959',
    projectId: 'glowify-final',
    storageBucket: 'glowify-final.firebasestorage.app',
    iosBundleId: 'com.example.glowify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsrPj6Y0TxxmOrus66MXkfJSyQDZ23u98',
    appId: '1:716525555959:ios:35ac28229ddd86120103f2',
    messagingSenderId: '716525555959',
    projectId: 'glowify-final',
    storageBucket: 'glowify-final.firebasestorage.app',
    iosBundleId: 'com.example.glowify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtTbL63HfuvcJAbKjQ6miLb8h5XmakI3o',
    appId: '1:716525555959:web:300bea2c58dc0c8c0103f2',
    messagingSenderId: '716525555959',
    projectId: 'glowify-final',
    authDomain: 'glowify-final.firebaseapp.com',
    storageBucket: 'glowify-final.firebasestorage.app',
  );
}
